export const initialData = [
  { title: "React", categories: ["Frontend"], experience: "+/- 8" },
  { title: "TypeScript", categories: ["Frontend"], experience: "+/- 8" },
  {
    title: "JavaScript",
    categories: ["Frontend", "Scripting"],
    experience: "+/- 10",
  },
  {
    title: "jQuery",
    categories: ["Frontend", "Library"],
    experience: "+/- 10",
  },
  {
    title: "jQuery UI",
    categories: ["Frontend", "Library"],
    experience: "+/- 3",
  },
  { title: "HTML", categories: ["Frontend"], experience: "+20" },
  {
    title: "Rest API",
    categories: ["Backend", "Data"],
    experience: "+/- 10",
  },
  {
    title: "PowerShell",
    categories: ["Backend", "Scripting"],
    experience: "+/- 3",
  },
  {
    title: "Python",
    categories: ["Backend", "Programming"],
    experience: "2",
  },
  { title: "BeautifulSoup", categories: ["Library"], experience: "1" },
  {
    title: "Entity Framework",
    categories: ["Backend", "Data"],
    experience: "+20",
  },
  { title: "MVC", categories: ["Design Pattern"], experience: "+20" },
  {
    title: ".Net C#",
    categories: ["Backend", "Frontend", "Programming"],
    experience: "+20",
  },
  {
    title: "Mantine",
    categories: ["Frontend", "Library"],
    experience: "+/- 5",
  },
  {
    title: "Bootstrap",
    categories: ["Frontend", "Library"],
    experience: "+/- 15",
  },
  {
    title: "Azure DevOps",
    categories: ["Code Management"],
    experience: "+20",
  },
  { title: "Git", categories: ["Code Management"], experience: "+/- 10" },
  { title: "YAML", categories: ["Scripting"], experience: "+/- 5" },
  { title: "Microsoft Azure", categories: ["Cloud"], experience: "+20" },
  { title: "OpenAI API", categories: ["Data"], experience: "1" },
  { title: "LESS", categories: ["Frontend"], experience: "+/- 10" },
  { title: "CSS", categories: ["Frontend"], experience: "+20" },
  { title: "SASS", categories: ["Frontend"], experience: "+20" },
  {
    title: "Progressive Web Apps",
    categories: ["Frontend", "Cross platform"],
    experience: "+/- 5",
  },
  {
    title: "PHP",
    categories: ["Frontend", "Backend", "Scripting"],
    experience: "+/- 10",
  },
  { title: "SQL", categories: ["Backend", "Data"], experience: "+/- 10" },
  {
    title: "CosmosDB",
    categories: ["Backend", "Data", "Cloud"],
    experience: "2",
  },
  { title: "Kontent.AI", categories: ["Backend", "CMS"], experience: "+20" },
  { title: "SharePoint", categories: ["Backend", "CMS"], experience: "+20" },
  {
    title: "Ionic",
    categories: ["Cross platform", "Frontend"],
    experience: "2",
  },
  {
    title: "Cordova",
    categories: ["Cross platform", "Frontend"],
    experience: "3",
  },
  {
    title: "PhoneGap",
    categories: ["Cross platform", "Frontend"],
    experience: "2",
  },
  {
    title: "React Native",
    categories: ["Cross platform", "Frontend"],
    experience: "1",
  },
  {
    title: "Mobile Application Development",
    categories: ["Cross platform"],
    experience: "+/- 10",
  },
  { title: "Adobe Photoshop", categories: ["Graphics"], experience: "+20" },
  {
    title: "Adobe Illustrator",
    categories: ["Graphics"],
    experience: "+/- 10",
  },
  {
    title: "Adobe Premiere Pro",
    categories: ["Graphics"],
    experience: "+/- 5",
  },
  { title: "3dsMax", categories: ["Graphics"], experience: "+/- 5" },
];
